// Generated by gir (https://github.com/gtk-rs/gir @ 0e476ab5c1de)
// from 
// from gir-files (https://github.com/gtk-rs/gir-files.git @ cfc0305f903b)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "LfbEventClass", sizeof(LfbEventClass), alignof(LfbEventClass));
    printf("%s;%zu;%zu\n", "LfbEventEndReason", sizeof(LfbEventEndReason), alignof(LfbEventEndReason));
    printf("%s;%zu;%zu\n", "LfbEventState", sizeof(LfbEventState), alignof(LfbEventState));
    printf("%s;%zu;%zu\n", "LfbGdbusFeedbackProxyClass", sizeof(LfbGdbusFeedbackProxyClass), alignof(LfbGdbusFeedbackProxyClass));
    printf("%s;%zu;%zu\n", "LfbGdbusFeedbackSkeletonClass", sizeof(LfbGdbusFeedbackSkeletonClass), alignof(LfbGdbusFeedbackSkeletonClass));
    return 0;
}
