// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files.git)
// DO NOT EDIT

use crate::{EventEndReason, EventState};
use glib::{
    prelude::*,
    signal::{connect_raw, SignalHandlerId},
    translate::*,
};
use std::{boxed::Box as Box_, pin::Pin};

glib::wrapper! {
    /// An event triggering feedback to the user
    ///
    /// #LfbEvent represents an event that should trigger
    /// audio, haptic and/or visual feedback to the user by triggering
    /// feedback on a feedback daemon. Valid event names are specified
    /// in the
    /// [Event naming specification](Event-naming-spec-0.0.0.html).
    ///
    /// One event can trigger multiple feedbacks at once (e.g. audio and
    /// haptic feedback). This is determined by the feedback theme in
    /// use (which is not under the appliction's control) and the active
    /// feedback profile (see [`set_feedback_profile()`][Self::set_feedback_profile()].
    ///
    /// After initializing the library via [`init()`][crate::init()] feedback can be
    /// triggered like:
    ///
    /// **⚠️ The following code is in c ⚠️**
    ///
    /// ```c
    ///   g_autoptr (GError) err = NULL;
    ///   LfbEvent *event = lfb_event_new ("message-new-instant");
    ///   lfb_event_set_timeout (event, 0);
    ///   if (!lfb_event_trigger_feedback (event, &err))
    ///     g_warning ("Failed to trigger feedback: %s", err->message);
    /// ```
    ///
    /// When all feedback for this event has ended the [`feedback-ended`][struct@crate::LfbEvent#feedback-ended]
    /// signal is emitted. If you want to end the feedback ahead of time use
    /// `LfbEvent::end_feedback()`:
    ///
    /// **⚠️ The following code is in c ⚠️**
    ///
    /// ```c
    ///   if (!lfb_event_end_feedback (event, &err))
    ///     g_warning ("Failed to end feedback: %s", err->message);
    /// ```
    ///
    /// Since these methods involve DBus calls there are asynchronous variants
    /// available, e.g. `LfbEvent::trigger_feedback_async()`:
    ///
    /// **⚠️ The following code is in c ⚠️**
    ///
    /// ```c
    ///   static void
    ///   on_feedback_triggered (LfbEvent      *event,
    ///                          GAsyncResult  *res,
    ///                          gpointer      unused)
    ///   {
    ///      g_autoptr (GError) err = NULL;
    ///      if (!lfb_event_trigger_feedback_finish (event, res, &err)) {
    ///         g_warning ("Failed to trigger feedback for %s: %s",
    ///                    lfb_event_get_event (event), err->message);
    ///      }
    ///   }
    ///
    ///   static void
    ///   my_function ()
    ///   {
    ///     LfbEvent *event = lfb_event_new ("message-new-instant");
    ///     lfb_event_trigger_feedback_async (event, NULL,
    ///                                      (GAsyncReadyCallback)on_feedback_triggered,
    ///                                      NULL);
    ///   }
    /// ```
    ///
    /// ## Properties
    ///
    ///
    /// #### `app-id`
    ///  The application id to use for the event.
    /// [`set_feedback_profile()`][crate::set_feedback_profile()] for details.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `end-reason`
    ///  Readable
    ///
    ///
    /// #### `event`
    ///  The type of event from the Event naming spec, e.g. 'message-new-instant'.
    ///
    /// Readable | Writeable | Construct Only
    ///
    ///
    /// #### `feedback-profile`
    ///  The name of the feedback profile to use for this event. See
    /// [`set_feedback_profile()`][crate::set_feedback_profile()] for details.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `important`
    ///  Whether to flag this event as important.
    /// `LfbEvent::set_imporant()` for details.
    ///
    /// Readable | Writeable
    ///
    ///
    /// #### `state`
    ///  Readable
    ///
    ///
    /// #### `timeout`
    ///  How long feedback should be provided in seconds. The special value
    /// %-1 uses the natural length of each feedback while `0` plays each feedback
    /// in a loop until ended explicitly via e.g. `LfbEvent::end_feedback()`.
    ///
    /// Readable | Writeable
    ///
    /// ## Signals
    ///
    ///
    /// #### `feedback-ended`
    ///  Emitted when all feedbacks triggered by the event have ended.
    ///
    ///
    #[doc(alias = "LfbEvent")]
    pub struct Event(Object<ffi::LfbEvent, ffi::LfbEventClass>);

    match fn {
        type_ => || ffi::lfb_event_get_type(),
    }
}

impl Event {
    /// Creates a new [`Event`][crate::Event] based on the given event
    /// name. See [`event`][struct@crate::Event#event] for details.
    /// ## `event`
    /// The event's name.
    ///
    /// # Returns
    ///
    /// The [`Event`][crate::Event].
    #[doc(alias = "lfb_event_new")]
    pub fn new(event: &str) -> Event {
        assert_initialized_main_thread!();
        unsafe { from_glib_full(ffi::lfb_event_new(event.to_glib_none().0)) }
    }

    // rustdoc-stripper-ignore-next
    /// Creates a new builder-pattern struct instance to construct [`Event`] objects.
    ///
    /// This method returns an instance of [`EventBuilder`](crate::builders::EventBuilder) which can be used to create [`Event`] objects.
    pub fn builder() -> EventBuilder {
        EventBuilder::new()
    }

    /// Tells the feedback server to end all feedback for the given event as
    /// soon as possible.
    ///
    /// # Returns
    ///
    /// [`true`] if successful. On error, this will return [`false`] and set
    ///          @error.
    #[doc(alias = "lfb_event_end_feedback")]
    pub fn end_feedback(&self) -> Result<(), glib::Error> {
        unsafe {
            let mut error = std::ptr::null_mut();
            let is_ok = ffi::lfb_event_end_feedback(self.to_glib_none().0, &mut error);
            debug_assert_eq!(is_ok == glib::ffi::GFALSE, !error.is_null());
            if error.is_null() {
                Ok(())
            } else {
                Err(from_glib_full(error))
            }
        }
    }

    /// Tells the feedback server to end all feedback for the given event as
    /// soon as possible.
    /// ## `cancellable`
    /// A #GCancellable to cancel the operation or [`None`].
    /// ## `callback`
    /// A #GAsyncReadyCallback to call when the request is satisfied or [`None`].
    #[doc(alias = "lfb_event_end_feedback_async")]
    pub fn end_feedback_async<P: FnOnce(Result<(), glib::Error>) + 'static>(
        &self,
        cancellable: Option<&impl IsA<gio::Cancellable>>,
        callback: P,
    ) {
        let main_context = glib::MainContext::ref_thread_default();
        let is_main_context_owner = main_context.is_owner();
        let has_acquired_main_context = (!is_main_context_owner)
            .then(|| main_context.acquire().ok())
            .flatten();
        assert!(
            is_main_context_owner || has_acquired_main_context.is_some(),
            "Async operations only allowed if the thread is owning the MainContext"
        );

        let user_data: Box_<glib::thread_guard::ThreadGuard<P>> =
            Box_::new(glib::thread_guard::ThreadGuard::new(callback));
        unsafe extern "C" fn end_feedback_async_trampoline<
            P: FnOnce(Result<(), glib::Error>) + 'static,
        >(
            _source_object: *mut glib::gobject_ffi::GObject,
            res: *mut gio::ffi::GAsyncResult,
            user_data: glib::ffi::gpointer,
        ) {
            let mut error = std::ptr::null_mut();
            let _ = ffi::lfb_event_end_feedback_finish(_source_object as *mut _, res, &mut error);
            let result = if error.is_null() {
                Ok(())
            } else {
                Err(from_glib_full(error))
            };
            let callback: Box_<glib::thread_guard::ThreadGuard<P>> =
                Box_::from_raw(user_data as *mut _);
            let callback: P = callback.into_inner();
            callback(result);
        }
        let callback = end_feedback_async_trampoline::<P>;
        unsafe {
            ffi::lfb_event_end_feedback_async(
                self.to_glib_none().0,
                cancellable.map(|p| p.as_ref()).to_glib_none().0,
                Some(callback),
                Box_::into_raw(user_data) as *mut _,
            );
        }
    }

    pub fn end_feedback_future(
        &self,
    ) -> Pin<Box_<dyn std::future::Future<Output = Result<(), glib::Error>> + 'static>> {
        Box_::pin(gio::GioFuture::new(self, move |obj, cancellable, send| {
            obj.end_feedback_async(Some(cancellable), move |res| {
                send.resolve(res);
            });
        }))
    }

    /// Returns the app-id for this event. If no app-id has been explicitly
    /// set, [`None`] is returned. The event uses the app-id returned by
    /// [`app_id()`][Self::app_id()] in this case.
    ///
    /// # Returns
    ///
    /// The set app-id for this event or [`None`].
    #[doc(alias = "lfb_event_get_app_id")]
    #[doc(alias = "get_app_id")]
    pub fn app_id(&self) -> glib::GString {
        unsafe { from_glib_none(ffi::lfb_event_get_app_id(self.to_glib_none().0)) }
    }

    /// Get the reason why the feadback ended.
    ///
    /// # Returns
    ///
    /// The reason why feedback ended.
    #[doc(alias = "lfb_event_get_end_reason")]
    #[doc(alias = "get_end_reason")]
    pub fn end_reason(&self) -> EventEndReason {
        unsafe { from_glib(ffi::lfb_event_get_end_reason(self.to_glib_none().0)) }
    }

    /// Get the event's name according to the event naming spec.
    ///
    /// # Returns
    ///
    /// The event name
    #[doc(alias = "lfb_event_get_event")]
    #[doc(alias = "get_event")]
    pub fn event(&self) -> glib::GString {
        unsafe { from_glib_none(ffi::lfb_event_get_event(self.to_glib_none().0)) }
    }

    /// Gets the set feedback profile. If no profile was set it returns
    /// [`None`]. The event uses the system wide profile in this case.
    ///
    /// # Returns
    ///
    /// The set feedback profile to use for this event or [`None`].
    #[doc(alias = "lfb_event_get_feedback_profile")]
    #[doc(alias = "get_feedback_profile")]
    pub fn feedback_profile(&self) -> glib::GString {
        unsafe { from_glib_none(ffi::lfb_event_get_feedback_profile(self.to_glib_none().0)) }
    }

    /// Gets the set feedback profile. If no profile was set it returns
    /// [`None`]. The event uses the system wide profile in this case.
    ///
    /// # Returns
    ///
    /// The set feedback profile to use for this event or [`None`].
    #[doc(alias = "lfb_event_get_important")]
    #[doc(alias = "get_important")]
    pub fn is_important(&self) -> bool {
        unsafe { from_glib(ffi::lfb_event_get_important(self.to_glib_none().0)) }
    }

    /// Get the current event state (e.g. if triggered feeedback is
    /// currently running.
    ///
    /// # Returns
    ///
    /// The state of the feedback triggered by event.
    #[doc(alias = "lfb_event_get_state")]
    #[doc(alias = "get_state")]
    pub fn state(&self) -> EventState {
        unsafe { from_glib(ffi::lfb_event_get_state(self.to_glib_none().0)) }
    }

    /// Get the currently set timeout.
    ///
    /// # Returns
    ///
    /// The event timeout in milliseconds
    #[doc(alias = "lfb_event_get_timeout")]
    #[doc(alias = "get_timeout")]
    pub fn timeout(&self) -> i32 {
        unsafe { ffi::lfb_event_get_timeout(self.to_glib_none().0) }
    }

    /// Tells the feedback server to use the given application id for
    /// this event when it is submitted. The server might ignore this
    /// request. This can be used by notification daemons to honor per
    /// application settings automatically.
    ///
    /// The functions is usually not used by applications.
    ///
    /// A value of [`None`] (the default) lets the server pick the profile.
    /// ## `app_id`
    /// The application id to use
    #[doc(alias = "lfb_event_set_app_id")]
    pub fn set_app_id(&self, app_id: &str) {
        unsafe {
            ffi::lfb_event_set_app_id(self.to_glib_none().0, app_id.to_glib_none().0);
        }
    }

    /// Tells the feedback server to use the given feedback profile for
    /// this event when it is submitted. The server might ignore this
    /// request.  Valid profile names and their 'noisiness' are specified
    /// in the [Feedback theme specification](Feedback-theme-spec-0.0.0.html).
    ///
    /// A value of [`None`] (the default) lets the server pick the profile.
    /// ## `profile`
    /// The feedback profile to use
    #[doc(alias = "lfb_event_set_feedback_profile")]
    pub fn set_feedback_profile(&self, profile: &str) {
        unsafe {
            ffi::lfb_event_set_feedback_profile(self.to_glib_none().0, profile.to_glib_none().0);
        }
    }

    /// Tells the feedback server that the sender deems this to be an
    /// important event. A feedback server might allow the sender to
    /// override the current feedback level when this is set.
    /// ## `important`
    /// Whether to flag this event as important
    #[doc(alias = "lfb_event_set_important")]
    pub fn set_important(&self, important: bool) {
        unsafe {
            ffi::lfb_event_set_important(self.to_glib_none().0, important.into_glib());
        }
    }

    /// Tells the feedback server to end feedack after #timeout seconds.
    /// The value -1 indicates to not set a timeout and let feedbacks stop
    /// on their own while 0 indicates to loop all feedbacks endlessly.
    /// They must be stopped via `LfbEvent::end_feedback()` in this case.
    ///
    /// It is an error to change the timeout after the feedback has been triggered
    /// via `LfbEvent::trigger_feedback()`.
    /// ## `timeout`
    /// The timeout
    #[doc(alias = "lfb_event_set_timeout")]
    pub fn set_timeout(&self, timeout: i32) {
        unsafe {
            ffi::lfb_event_set_timeout(self.to_glib_none().0, timeout);
        }
    }

    /// Tells the feedback server to provide proper feedback for the give
    /// event to the user.
    ///
    /// # Returns
    ///
    /// [`true`] if successful. On error, this will return [`false`] and set
    ///          @error.
    #[doc(alias = "lfb_event_trigger_feedback")]
    pub fn trigger_feedback(&self) -> Result<(), glib::Error> {
        unsafe {
            let mut error = std::ptr::null_mut();
            let is_ok = ffi::lfb_event_trigger_feedback(self.to_glib_none().0, &mut error);
            debug_assert_eq!(is_ok == glib::ffi::GFALSE, !error.is_null());
            if error.is_null() {
                Ok(())
            } else {
                Err(from_glib_full(error))
            }
        }
    }

    /// Tells the feedback server to provide proper feedback for the give
    /// event to the user. This is the sync version of
    /// `LfbEvent::trigger_feedback()`.
    /// ## `cancellable`
    /// A #GCancellable to cancel the operation or [`None`].
    /// ## `callback`
    /// A #GAsyncReadyCallback to call when the request is satisfied or [`None`].
    #[doc(alias = "lfb_event_trigger_feedback_async")]
    pub fn trigger_feedback_async<P: FnOnce(Result<(), glib::Error>) + 'static>(
        &self,
        cancellable: Option<&impl IsA<gio::Cancellable>>,
        callback: P,
    ) {
        let main_context = glib::MainContext::ref_thread_default();
        let is_main_context_owner = main_context.is_owner();
        let has_acquired_main_context = (!is_main_context_owner)
            .then(|| main_context.acquire().ok())
            .flatten();
        assert!(
            is_main_context_owner || has_acquired_main_context.is_some(),
            "Async operations only allowed if the thread is owning the MainContext"
        );

        let user_data: Box_<glib::thread_guard::ThreadGuard<P>> =
            Box_::new(glib::thread_guard::ThreadGuard::new(callback));
        unsafe extern "C" fn trigger_feedback_async_trampoline<
            P: FnOnce(Result<(), glib::Error>) + 'static,
        >(
            _source_object: *mut glib::gobject_ffi::GObject,
            res: *mut gio::ffi::GAsyncResult,
            user_data: glib::ffi::gpointer,
        ) {
            let mut error = std::ptr::null_mut();
            let _ =
                ffi::lfb_event_trigger_feedback_finish(_source_object as *mut _, res, &mut error);
            let result = if error.is_null() {
                Ok(())
            } else {
                Err(from_glib_full(error))
            };
            let callback: Box_<glib::thread_guard::ThreadGuard<P>> =
                Box_::from_raw(user_data as *mut _);
            let callback: P = callback.into_inner();
            callback(result);
        }
        let callback = trigger_feedback_async_trampoline::<P>;
        unsafe {
            ffi::lfb_event_trigger_feedback_async(
                self.to_glib_none().0,
                cancellable.map(|p| p.as_ref()).to_glib_none().0,
                Some(callback),
                Box_::into_raw(user_data) as *mut _,
            );
        }
    }

    pub fn trigger_feedback_future(
        &self,
    ) -> Pin<Box_<dyn std::future::Future<Output = Result<(), glib::Error>> + 'static>> {
        Box_::pin(gio::GioFuture::new(self, move |obj, cancellable, send| {
            obj.trigger_feedback_async(Some(cancellable), move |res| {
                send.resolve(res);
            });
        }))
    }

    /// Emitted when all feedbacks triggered by the event have ended.
    #[doc(alias = "feedback-ended")]
    pub fn connect_feedback_ended<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn feedback_ended_trampoline<F: Fn(&Event) + 'static>(
            this: *mut ffi::LfbEvent,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"feedback-ended\0".as_ptr() as *const _,
                Some(std::mem::transmute::<_, unsafe extern "C" fn()>(
                    feedback_ended_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "app-id")]
    pub fn connect_app_id_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_app_id_trampoline<F: Fn(&Event) + 'static>(
            this: *mut ffi::LfbEvent,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::app-id\0".as_ptr() as *const _,
                Some(std::mem::transmute::<_, unsafe extern "C" fn()>(
                    notify_app_id_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "end-reason")]
    pub fn connect_end_reason_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_end_reason_trampoline<F: Fn(&Event) + 'static>(
            this: *mut ffi::LfbEvent,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::end-reason\0".as_ptr() as *const _,
                Some(std::mem::transmute::<_, unsafe extern "C" fn()>(
                    notify_end_reason_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "feedback-profile")]
    pub fn connect_feedback_profile_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_feedback_profile_trampoline<F: Fn(&Event) + 'static>(
            this: *mut ffi::LfbEvent,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::feedback-profile\0".as_ptr() as *const _,
                Some(std::mem::transmute::<_, unsafe extern "C" fn()>(
                    notify_feedback_profile_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "important")]
    pub fn connect_important_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_important_trampoline<F: Fn(&Event) + 'static>(
            this: *mut ffi::LfbEvent,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::important\0".as_ptr() as *const _,
                Some(std::mem::transmute::<_, unsafe extern "C" fn()>(
                    notify_important_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "state")]
    pub fn connect_state_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_state_trampoline<F: Fn(&Event) + 'static>(
            this: *mut ffi::LfbEvent,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::state\0".as_ptr() as *const _,
                Some(std::mem::transmute::<_, unsafe extern "C" fn()>(
                    notify_state_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }

    #[doc(alias = "timeout")]
    pub fn connect_timeout_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_timeout_trampoline<F: Fn(&Event) + 'static>(
            this: *mut ffi::LfbEvent,
            _param_spec: glib::ffi::gpointer,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(&from_glib_borrow(this))
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"notify::timeout\0".as_ptr() as *const _,
                Some(std::mem::transmute::<_, unsafe extern "C" fn()>(
                    notify_timeout_trampoline::<F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl Default for Event {
    fn default() -> Self {
        glib::object::Object::new::<Self>()
    }
}

// rustdoc-stripper-ignore-next
/// A [builder-pattern] type to construct [`Event`] objects.
///
/// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct EventBuilder {
    builder: glib::object::ObjectBuilder<'static, Event>,
}

impl EventBuilder {
    fn new() -> Self {
        Self {
            builder: glib::object::Object::builder(),
        }
    }

    /// The application id to use for the event.
    /// [`set_feedback_profile()`][crate::set_feedback_profile()] for details.
    pub fn app_id(self, app_id: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("app-id", app_id.into()),
        }
    }

    /// The type of event from the Event naming spec, e.g. 'message-new-instant'.
    pub fn event(self, event: impl Into<glib::GString>) -> Self {
        Self {
            builder: self.builder.property("event", event.into()),
        }
    }

    /// The name of the feedback profile to use for this event. See
    /// [`set_feedback_profile()`][crate::set_feedback_profile()] for details.
    pub fn feedback_profile(self, feedback_profile: impl Into<glib::GString>) -> Self {
        Self {
            builder: self
                .builder
                .property("feedback-profile", feedback_profile.into()),
        }
    }

    /// Whether to flag this event as important.
    /// `LfbEvent::set_imporant()` for details.
    pub fn important(self, important: bool) -> Self {
        Self {
            builder: self.builder.property("important", important),
        }
    }

    /// How long feedback should be provided in seconds. The special value
    /// %-1 uses the natural length of each feedback while `0` plays each feedback
    /// in a loop until ended explicitly via e.g. `LfbEvent::end_feedback()`.
    pub fn timeout(self, timeout: i32) -> Self {
        Self {
            builder: self.builder.property("timeout", timeout),
        }
    }

    // rustdoc-stripper-ignore-next
    /// Build the [`Event`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> Event {
        self.builder.build()
    }
}
