// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files.git)
// DO NOT EDIT

mod event;
pub use self::event::Event;

mod enums;
pub use self::enums::EventEndReason;
pub use self::enums::EventState;

pub(crate) mod functions;

pub(crate) mod builders {
    pub use super::event::EventBuilder;
}
