[package]
name = "libfeedback"
version = "0.0.1"
authors = ["Guido Günther <agx@sigxcpu.org>"]
edition = "2021"
readme = "../README.md"
homepage = "https://guidog.pages.gitlab.gnome.org/libfeedback-rs/"
description = "Rust bindings for libfeedback"
license = "MIT"
repository = "https://guidog.pages.gitlab.gnome.org/libfeedback-rs/"
documentation = "https://guidog.pages.gitlab.gnome.org/libfeedback-rs/stable/latest/docs/libfeedbac"
categories = ["api-bindings"]
keywords = ["gnome", "phosh", "feedbackd"]

[lib]
name = "libfeedback"

[features]
v0_3 = ["ffi/v0_3"]

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
libc = '0.2'

[dependencies.glib]
version = "0.19"
features = [ "v2_66" ]

[dependencies.gio]
version = "0.19"
features = [ "v2_70" ]

[dependencies.ffi]
package = "libfeedback-sys"
path = './sys'
version = "0.0.1"
